### PR TITLE
GSoD 2020 issues

### PR DESCRIPTION
**Pull request by pranay-simejia**
#### Changes done:
- [x] Task 1: All paths to images are corrected.

#### Screenshots:
image

#### ✅️ By submitting this PR, I have verified the following

- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add a link from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Review by Shivansh2407 — APPROVED** [review]
Great Work @pranay-simejia . LGTM 👍 @satu0king Please have a look and we will merge this PR by adding the Video Links in the specified places.

**Comment by pranay-simejia** [comment]
@Shivansh2407, shall I fix the open issues in this PR?

**Comment by Shivansh2407** [comment]
Yeah go ahead @pranay-simejia . You can list the existing issues and start working on it, make a Draft and keep it ready. As soon as we merge #282, we'll merge the draft PR too! Also make sure to fix the conflicts.

**Comment by tachyons** [comment]
Hi @pranay-simejia Can you rebase and fix conflicts so that we can merge this branch ?

**Comment by tachyons** [comment]
Merged manually

**Pull request closed without merging**
