### PR TITLE
Bring navbar menu button to top left corner

### LINKED ISSUE #139: Fix mobile navbar menu to top left
**Is your feature request related to a problem? Please describe.**
Mobile navbar menu in CircuitVerse's documentation is fixed at bottom left now, making it hard to find. 

**Describe the solution you'd like**
Fix mobile navigation menu bar to top left

**Additional context**
image

### PR DESCRIPTION
**Pull request by SamriddhiMishra**
Fixes #139

### CODE REVIEW

**Comment by SamriddhiMishra** [comment]
Please review!
Excuse me for any mistake, I am kind of new to this. Thanks!

**Comment by tachyons** [comment]
Hi  SamriddhiMishra , welcome to circuitverse community. It seems that you overrided entire theme file which will make application more difficult to maintain. also it is difficult to understand what is being changed, So override styles in separate stylesheet if you need to

**Comment by SamriddhiMishra** [comment]
Is it alright if I change only the index.html file and the theme file or any other.

**Comment by SamriddhiMishra** [comment]
Is it alright if I change only the index.html file and not any other file?

**Pull request closed without merging**
