### PR TITLE
Added command for local deployment testing

### LINKED ISSUE #247: Local Deployment Issue
#### I am submitting a -
* [] **Feature Request**

#### Screenshots (if relevant) -
Screenshot (122)

#### Are you working on this issue? (Yes/No)
Yes

### PR DESCRIPTION
**Pull request by nileshdas**
Fixes #247

#### Changes done:
- [x] Added a deployment command for smoother local testing

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by nileshdas** [comment]
Can't figure out why there's a conflict. Can anyone suggest something?

**Comment by nileshdas** [comment]
Done!

**Comment by nileshdas** [comment]
Deploy link: https://app.netlify.com/sites/youthful-dijkstra-240fec/settings/deploys#continuous-deployment

**Comment by YashKumarVerma** [comment]
Thanks a lot for your contributions.

**Pull request merged**
