### PR TITLE
Changed dark theme contrast colour from Red --> Green (to match CircuitVerse theme)

### LINKED ISSUE #162: Change complementary color of Dark Mode
#### I am submitting a -
* [x] **Feature Request**
* [] **Bug Report**

#### Describe your bug/feature -
Complementary color of Dark Mode is not much attractive currently. 
Click on this link https://docs.circuitverse.org/ and then toggle on the Dark Mode

#### Current behaviour -
Current color is RED with Dark Mode.
Screenshot (1897)

#### Expected behaviour -
Color should be a bit attractive like Green or something else. The following Screenshot is in the Google Pixel 2 view.
docs circuitverse org_(Pixel 2)

#### Screenshots (if relevant) - 
Uploaded

#### Are you working on this issue? (Yes/No)
Yes, I would like to

### PR DESCRIPTION
**Pull request by schezfaz**
Fixes #162 

Ref #226 [the changes for this PR had been overwritten, however since this PR also deals with fixing the dark-theme, the overwritten changes have been implicitly reinstated]

#### Changes done:
- [x] Overwrote the [default docsify dark theme](//unpkg.com/docsify/themes/dark.css) colour from #EA6F5A (tera cotta) to #42B983 (medium sea green) to match the CircuitVerse theme and logo. Changes in:     
  - styles/darkTheme.css
  - index.html

- [x] Changed the slider colour to medium sea green (to match the dark theme). Changes in: 
    - styles/theme.css

#### Screenshots:
Slider colour (in light mode):
image

#### Preview Link:
https://deploy-preview-243--blissful-einstein-93d693.netlify.app/#/

#### ✅️ By submitting this PR, I have verified the following
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by schezfaz** [comment]
Ohno, working on fixing this!

**Comment by nileshdas** [comment]
@schezfaz Are you working on it?

**Comment by schezfaz** [comment]
@nileshdas hi yes, will push the changes in a day or so. Been having a lot of issues with my machine 😭

**Comment by schezfaz** [comment]
@nileshdas Hi, I am not working on this issue currently. Please take it forward if you'd like!

**Pull request closed without merging**
