### PR TITLE
Github pages give 404 on refresh #231

### LINKED ISSUE #231: Github pages give 404 on refresh
#### I am submitting a -
* [ ] **Feature Request**
* [x] **Bug Report**

#### Describe your bug -
All pages except the home page give a 404 error on refresh.

#### Current behaviour -
As stated, only the main page works on refresh. No other pages work.

#### Expected behaviour -
All pages work the same on refresh.

#### Screenshots (if relevant) -
Screenshot from 2020-05-22 12-19-58
Screenshot from 2020-05-22 12-20-02

#### Are you working on this issue? (Yes/No)
This is a high priority issue as far as UX is concerned. All suggestions are welcome.

### PR DESCRIPTION
**Pull request by Umoren**
Fixes #231 
- All pages except the home page give a 404 error on refresh.
Ref #

#### Changes done:
    - I changed ```routerMode: history ``` to ```routerMode: hash```
- [x] Task 1

#### ✅️ By submitting this PR, I have verified the following

- [x ] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
Ideally, you should switch branches for every PR created. Please keep that in mind @Umoren .

**Comment by ShubhankarKG** [comment]
@Umoren please provide a preview link from the checks tab.

**Comment by Umoren** [comment]
I had some issues.
I deleted this branch.
I just pushed the new branch for this

**Comment by Umoren** [comment]
Thanks for your patience.
I've resolved the merge conflict

**Comment by Umoren** [comment]
Preview Link
https://deploy-preview-232--blissful-einstein-93d693.netlify.app/#/Modify
https://media.giphy.com/media/U4SfAuRfJ5qczUY97c/giphy.gif

**Comment by Shivansh2407** [comment]
True, @Umoren try to squash the commits into one from next time onwards as suggested in the PR template👍

**Comment by Umoren** [comment]
Alright.
I'm still new to squashing commits.
But I've figured it out now.
Would do so next time.

I created a new issue #237

**Pull request merged**
