### PR TITLE
LMS Integration doc Update - GSoC'21 Ayan Biswas

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
#### Changes done:
- [x] Added ```docs/lms_integration.md```.
- [x] Written documentation about how to use CircuitVerse as an LTI External Tool with different LMS
- [x] Written documentation about how to add CircuitVerse with LMSs
   - [x] Written instructions for Moodle
   - [x] Written instructions for Canvas
   - [x] Written instructions for Sakai
   - [x] Any other generic LTI Supported LMS

#### Screenshots:
image
image
image
image
image

#### Preview Link(s):
1. https://deploy-preview-301--wizardly-perlman-2ed351.netlify.app/#/lms_integration
2. https://deploy-preview-301--blissful-einstein-93d693.netlify.app/#/lms_integration

#### ✅️ By submitting this PR, I have verified the following

- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Review by ShreyaPrasad1209 — CHANGES_REQUESTED** [review]
@ayan-biswas0412 first resolve all the typo issues raised by Typo CI.

**Review by ShreyaPrasad1209 — COMMENTED** [review]
Everything looks good to me @ayan-biswas0412 🎉

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 first resolve all the typo issues raised by Typo CI.

sure

**Comment by ayan-biswas0412** [comment]
> Everything looks good to me @ayan-biswas0412 🎉

Thanks for reviewing 🎉

**Comment by ayan-biswas0412** [comment]
@ShreyaPrasad1209 please undo this merge, 
this supposed to be merged after LMS integration whole project work is in master of actual repo

**Comment by Shivansh2407** [comment]
> @ShreyaPrasad1209 please undo this merge,
> this supposed to be merged after LMS integration whole project work is in master of actual repo

Yeah @ShreyaPrasad1209 , Firstly we need to merge the GSoD 2020 work, and then We need to refine the LMS doc as well, after the Project is completed. Thanks 👍🏻

**Comment by ShreyaPrasad1209** [comment]
@Shivansh2407 it's reverted already.

**Pull request merged**
