### PR TITLE
Added feature 

### LINKED ISSUE #55: Reading experience in dark theme
#### I am submitting a -
* [] **Feature Request**
#### Describe your feature -
      Dark theme reading
#### Are you working on this issue? (Yes/No)
  yes

### PR DESCRIPTION
**Pull request by harsha-iiiv**
Fixes #55 

#### Describe the changes you have made -
 Added dark theme css file
#### Screenshots of the changes (If any) -

video-encode

### CODE REVIEW

**Comment by harsha-iiiv** [comment]
Dev link

 http://838740d0.ngrok.io

**Comment by satu0king** [comment]
Looks nice but it is taking too much space on the top. Move it to the right, also it doesn't look like a theme option. Either label it as theme or at least give the circles different color.

**Comment by harsha-iiiv** [comment]
Ok sure, I will look into this and thanks @satu0king

**Comment by satu0king** [comment]
I believe this is already merged now.

**Pull request closed without merging**
