### PR TITLE
Section for Embedding circuits added

### LINKED ISSUE #262: Adding Documentation for embedding circuits for new contributors
## Is your feature request related to a problem? Please describe.
Currently there's no documentation as to how circuits should be embedded in the documentation for new contributors. I too felt the need of it when I started.

## Describe the solution you'd like
writing a separate section describing steps for the same

### PR DESCRIPTION
**Pull request by CapTen101**
Fixes #262 - Adding Documentation for embedding circuits for new contributors

#### Changes done:
- [x] Added a separate section - guide for embedding in documentation/webpages

#### Screenshots:

Screenshot from 2020-06-26 21-06-59
Screenshot from 2020-06-26 21-07-03
Screenshot from 2020-06-26 21-07-07
Screenshot from 2020-06-26 21-07-10

#### Preview Link(s):

https://deploy-preview-268--blissful-einstein-93d693.netlify.app/#/

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by CapTen101** [comment]
@Shivansh2407 @YashKumarVerma Now it's looking clean and sweet with a single commit :smile: 
Kindly have a look

**Comment by CapTen101** [comment]
> Nice Work @CapTen101 👍 . Should we also add embedding circuit in docs here? Also make the srccode.png center aligned.

@Shivansh2407 Actually I didn't understand here what you meant by `add embedding circuits here in docs`. Can you elaborate a little on that😅.
And sure, I'll make it centre aligned 👍

**Comment by Shivansh2407** [comment]
These circuits can be embedded anywhere (apart from the documentation)

You have mentioned this in the starting of the page, so I was thinking to add a tutorial on how can users contribute to CV by embedding new circuits in docs.
Let me know your views.

**Comment by CapTen101** [comment]
@Shivansh2407 Actually this tutorial is works for everywhere. Even for contributing to CV docs, there is a line which mentions about the same (line 29). It's already present there. Have a look. That line mentions how to add the circuit in the docs

**Comment by Shivansh2407** [comment]
Cool then, just center align the image and we will be good to go👍

**Comment by CapTen101** [comment]
Ok, cool👍🙂

**Comment by CapTen101** [comment]
I've center sligned the images, squashed commits and updated the screenshots. @Shivansh2407 Kindly have a look :)

**Pull request merged**
