### PR TITLE
Fixing Broken links in docs

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes #https://github.com/CircuitVerse/CircuitVerseDocs/issues/134
GCI task link : https://codein.withgoogle.com/dashboard/task-instances/6217892190748672/

#### Describe the changes you have made -

- iframe contents have been left as such.
- Fixed broken links

### CODE REVIEW

**Comment by aayush-05** [comment]
Attach some screenshots as well @Ananthavijay

**Comment by Ananthavijay** [comment]
Screenshot (95)
Screenshot (96)
Screenshot (97)
Screenshot (98)
Screenshot (99)
Screenshot (100)

**Comment by Ananthavijay** [comment]
As seen from the screenshots, now the images are visible in .md files also

**Comment by Ananthavijay** [comment]
Pls review @aayush-05

**Pull request closed without merging**
