### PR TITLE
Changed Dark Mode Theme Color and Font

### LINKED ISSUE #162: Change complementary color of Dark Mode
#### I am submitting a -
* [x] **Feature Request**
* [] **Bug Report**

#### Describe your bug/feature -
Complementary color of Dark Mode is not much attractive currently. 
Click on this link https://docs.circuitverse.org/ and then toggle on the Dark Mode

#### Current behaviour -
Current color is RED with Dark Mode.
Screenshot (1897)

#### Expected behaviour -
Color should be a bit attractive like Green or something else. The following Screenshot is in the Google Pixel 2 view.
docs circuitverse org_(Pixel 2)

#### Screenshots (if relevant) - 
Uploaded

#### Are you working on this issue? (Yes/No)
Yes, I would like to

### PR DESCRIPTION
**Pull request by nileshdas**
Fixes #162 and #140 

#### Changes done:
- [x] Changed dark mode theme color
- [x] Changed Font family for better readability

#### Screenshots:
Screenshot (182)
Screenshot (183)

#### Preview Link(s):
https://deploy-preview-266--blissful-einstein-93d693.netlify.app/#/

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Started a poll on slack channel for the changes, since opinions can vary on this. 

https://circuitverse-team.slack.com/archives/CJU3KUX29/p1592851114113500

**Comment by nileshdas** [comment]
Capture
I agree with the reviews received, Open Sans would be better. Or we could just drop the font change for another issue. Reviews @YashKumarVerma @Shivansh2407

**Comment by YashKumarVerma** [comment]
> Capture
> I agree with the reviews received, Open Sans would be better. Or we could just drop the font change for another issue. Reviews @YashKumarVerma @Shivansh2407

I think it would not be apt to change fonts first in this PR and then have another pr for that font. If it's clear that it has to be changed, why not do it in this PR itself ?

**Comment by nileshdas** [comment]
Changed it. Have a look @YashKumarVerma 
Preview Link: https://deploy-preview-266--blissful-einstein-93d693.netlify.app/#/subcircuit

**Comment by nileshdas** [comment]
CC :  @Shivansh2407

**Pull request merged**
