### PR TITLE
Reorder files

### PR DESCRIPTION
**Pull request by fdila**
Move documentation files to /docs

### CODE REVIEW

**Comment by satu0king** [comment]
You will have to move all the files into the docs folder. The only file in the root should be readme.md

**Comment by fdila** [comment]
It should be ok now

**Comment by satu0king** [comment]
It looks correct, However, I am unable to resolve the conflicts? Maybe you can rebase your branch with master or send a new PR.

**Comment by fdila** [comment]
I opened a new pull request here https://github.com/CircuitVerse/CircuitVerseDocs/pull/26

**Pull request closed without merging**
