### PR TITLE
Keyboard shortcuts docs#2981

### PR DESCRIPTION
**Pull request by ahmedibrahim404**
Fixes https://github.com/CircuitVerse/CircuitVerse/issues/2981

#### Changes done:
- [Add markdown file for chapter 9(keyboard shortcuts)](https://github.com/CircuitVerse/CircuitVerseDocs/commit/bdad6c6e61a1c766f81782591c4e597ef4117d2a)[](https://github.com/ahmedibrahim404)

I think if there is any keys missing, I still can add it the next days when I figure it out! 
I searched in the codebase and this is the keys I could find 

#### Screenshots:
image

### CODE REVIEW

**Comment by devartstar** [comment]
Hi, @ahmedibrahim404 Nice work.
You can also find some of the shortcut keys on doing
`Simulator -> Inspect -> Storage -> LocalStorage -> Key:defaultKeys`

Shortcutkeys

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please add it under Chapter 8 instead of creating a new chapter

**Comment by ahmedibrahim404** [comment]
@ayan-biswas0412
Could you check it now?

**Review by ayan-biswas0412 — APPROVED** [review]
Good work @ahmedibrahim404 🎉
LGTM @manjotsidhu

**Comment by manjotsidhu** [comment]
@tachyons Approve workflow for this PR

**Review by manjotsidhu — APPROVED** [review]

**Pull request merged**
