### PR TITLE
Add main website link

### PR DESCRIPTION
**Pull request by JoshHeng**
Fixes: no link to the main website on the documention pages (issue https://github.com/CircuitVerse/CircuitVerseDocs/issues/170)

#### Describe the changes you have made -
- I have added the CircuitVerse logo which links to the main website. This is in the place of the original `CircuitVerse Documentation` hyperlink which only redirected to the home page (which can already be accessed with the `home` button)
- I have also tidied up the index.html code

#### Screenshots of the changes  -
See the logo in the top left corner
firefox_7KvC7BppS9

### CODE REVIEW

**Comment by JoshHeng** [comment]
@sal2701

**Comment by sal2701** [comment]
Hey @JoshHeng good work. But I have a few concerns:
* The title **CircuitVerse Documentation** needs to be there on the website, so do not remove the name and keep the link above the name or above the search bar.
* Also, the image added doesn't look proper in the dark mode, try adding a button or add separate images for both the modes. You can find the images [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/public/img/circuitverse2.svg) and [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/public/img/circuitverse_black.svg).

Try making these changes and let me know if you need any help.

**Comment by JoshHeng** [comment]
@sal2701 Issues have been fixed

**Comment by JoshHeng** [comment]
Issue fixed. For some reason nothing can go before the search field or it will break, so I've added the logo after.
firefox_lqPp3drTrn

**Comment by JoshHeng** [comment]
@sal2701

**Comment by sal2701** [comment]
Awesome work @JoshHeng, looks great. A few final touches, I feel we can get rid of the Circuitverse in "Circuitverse Documentation"  and keep it as "Documentation", as there is the logo above. What do you think?

**Comment by JoshHeng** [comment]
Done

**Comment by sal2701** [comment]
Cool @JoshHeng! Thanks for your contribution :smile:

**Comment by JoshHeng** [comment]
@sal2701 Please could you confirm the GCI task, thanks

**Comment by JoshHeng** [comment]
Resolved issue

**Comment by sal2701** [comment]
@tachyons please review this

**Comment by JoshHeng** [comment]
Duplicate so closing

**Pull request closed without merging**
