### PR TITLE
corrected path of test_bench.mp4

### LINKED ISSUE #228: testbench.mp4 file is not found in testbench docs
#### I am submitting a -
* [] **Feature Request**
* [x] **Bug Report**

#### Describe your bug/feature -
Testbench.mp4 file not found

#### Current behaviour -
testbench.mp4 file is not found in testbench docs
#### Expected behaviour -
adding testbench.mp4 file as testbench.gif in testbench docs

#### Are you working on this issue? (Yes/No)
yes

### PR DESCRIPTION
**Pull request by animesh-007**
Fixes #228 

Ref #228 

#### Changes done:
- [x] Task 1

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

[Preview link](https://deploy-preview-239--wizardly-perlman-2ed351.netlify.app/#/testbench)

### CODE REVIEW

**Comment by animesh-007** [comment]
> I think it would be better if a Gif of screen recording is placed instead of the video. Please let me know views.

But in that case, it will increase the size of the file like 4-6 times.
I m asking this because I tried to convert mp4 into a gif on getting_started.md
[Ref](https://github.com/CircuitVerse/CircuitVerseDocs/pull/227#pullrequestreview-415883960)

**Comment by YashKumarVerma** [comment]
> I think it would be better if a Gif of screen recording is placed instead of the video. Please let me know views.

What do you think ? should we go with gif with bigger sizes or video with smaller size ?

**Comment by nileshdas** [comment]
The video has weird noises, it would be better to use a muted video

**Comment by nileshdas** [comment]
Yes, there's noise. I guess the recorder left the microphone on. A muted video will be better imo

**Comment by nileshdas** [comment]
I think he is not active. Should I make a PR instead?

**Comment by Shivansh2407** [comment]
> I think he is not active. Should I make a PR instead?

Let's just wait for a day or two for @animesh-007 to respond. Otherwise you can continue with the PR.

**Comment by animesh-007** [comment]
> > I think he is not active. Should I make a PR instead?
> 
> Let's just wait for a day or two for @animesh-007 to respond. Otherwise you can continue with the PR.

Sorry for not being active too much. I will do the suggested changes.

**Comment by animesh-007** [comment]
I have removed the background audio from the video. Are we going with a video or gif?

**Comment by Shivansh2407** [comment]
At first I thought of going with GIFs but later on if we need to add any tutorial so we will be adding it in video format because user may pause it anytime they want. Hence Video format should be taken. Here can we get a clear video as the text in elements is visible in fullscreen, but in normal page it gets blurred. Please check and update it soon.

**Comment by animesh-007** [comment]
> At first I thought of going with GIFs but later on if we need to add any tutorial so we will be adding it in video format because user may pause it anytime they want. Hence Video format should be taken. Here can we get a clear video as the text in elements is visible in fullscreen, but in normal page it gets blurred. Please check and update it soon.

Video is clear it's just that text in middleboxes is very light still I increased the height of the video to make it more readable.

**Comment by animesh-007** [comment]
> It would be better if we can do something like : Open the Video( in a modal/popup ) on clicking the video so that we get see enlarged videos everytime rather than increasing the height of the video. Please make it available for mobile too @animesh-007 👍

@Shivansh2407 Can you let me know whether current modal structure is fine or not so that I can try to apply this for mobile mode too.

**Comment by Shivansh2407** [comment]
The modal looks good to me. The thing is, currently it is being overlapped by the sidebar and also the height is too much. Please fix these issues and make it mobile ready too @animesh-007 👍

**Comment by animesh-007** [comment]
> The modal looks good to me. The thing is, currently it is being overlapped by the sidebar and also the height is too much. Please fix these issues and make it mobile ready too @animesh-007 👍

I have made the suggested changes now. If any more changes you would like to have do let me know😀

**Comment by animesh-007** [comment]
> image
> Is the issue of video overflowing from the modal currently prevailing? Also Modal gets hidden due to the sidebar. Because what I can see in the preview link is this only. Please check and update the preview link and the screenshots.

Screen Shot 2020-06-28 at 3 16 13 PM
I don't see any overflowing and hiding of modal due to the sidebar. Here's the screenshot of it.

**Pull request merged**
