### PR TITLE
Fixed wire section issue

### LINKED ISSUE #242: Update wire section
#### I am submitting a -
* [x] **Feature Request**

#### Describe your bug/feature -
update connecting wires section https://docs.circuitverse.org/#/getting_started?id=connecting-wires
with this new feature 
https://github.com/CircuitVerse/CircuitVerse/pull/1351
#### Are you working on this issue? (Yes/No)
NO

### PR DESCRIPTION
**Pull request by Umoren**
Fixes #242 

Ref #

#### Changes done:
- [x] Added wire.mp4 to wire section

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x ] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Umoren** [comment]
Deploy Preview Link: https://deploy-preview-246--blissful-einstein-93d693.netlify.app/#/getting_started

**Comment by mahmodHammad** [comment]
I said update the "connecting wires section" with the new feature (CTRL + CLICKS).

 we should keep the drag as it is. while illustrating the new feature

**Comment by mahmodHammad** [comment]
you could say "we have two methods"
then put the 2 methods under them (draggin node, CTRL+clicking)

**Comment by CapTen101** [comment]
I think you can close this PR since the correct one has already been raised by you :slightly_smiling_face:

**Pull request closed without merging**
