### PR TITLE
Update index.html

### LINKED ISSUE #55: Reading experience in dark theme
#### I am submitting a -
* [] **Feature Request**
#### Describe your feature -
      Dark theme reading
#### Are you working on this issue? (Yes/No)
  yes

### PR DESCRIPTION
**Pull request by harsha-iiiv**
Fixes #55 
 

#### Screenshots of the changes (If any) -
dark

### CODE REVIEW

**Comment by harsha-iiiv** [comment]
@satu0king  Please review!

**Comment by satu0king** [comment]
Have a label on it which says theme

**Comment by harsha-iiiv** [comment]
screencast-localhost-8000-2019 04 01-14-47-49

**Comment by harsha-iiiv** [comment]
Is it looking good ?  @satu0king

**Pull request merged**
