### PR TITLE
Search bar position fixed Fixes #290 #311

### LINKED ISSUE #290: Menu icon not translucent and search bar position not fixed.
## Describe the bug
Menu icon's div is translucent.

## To Reproduce
1. Go to 'https://docs.circuitverse.org/#/outputs'
2. See error

## Expected behavior
Search bar should be fixed adjacent to the menu icon for better UX.

##Relevant screenshots.
image

## Are you working on this issue? (Yes/No)
Yes.

### LINKED ISSUE #311: Search bar should stick at the top while scrolling in the documentation page
**Describe the bug**
in the sidebar of documentation page "type here to search option is not fixed"
it should be fixed which will help user to search anything easily at any time 

Initially it is like this 

one

After scrolling it hides 
two

it should not hide at scroll 
one

**To Reproduce**
1. Go to 'Circuitverse.org'
2. Click on 'Getting Started'
3. Click on 'Documentation'
4. Scroll down left sidebar

**Expected behavior**

one

**Device Information :**
 - OS: Windows
 - Browser chrome

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes i am working on this issue .

### PR DESCRIPTION
**Pull request by Palaksharma23**
Fixes #290
Fixes #311 

#### Changes done:
- I have made the search position fixed on scroll 

#### Initially

https://user-images.githubusercontent.com/87171452/143035654-8a05ce55-4b41-4901-9849-90160341dc83.mp4

#### Finally 

https://user-images.githubusercontent.com/87171452/143035494-663d5a2f-e445-4a16-a311-2c572b0e08db.mp4

#### ✅️ By submitting this PR, I have verified the following

- [yes] Checked to see if a similar PR has already been opened 🤔️
- [yes] Reviewed the contributing guidelines 🔍️
- [yes] Sample preview link added (add a link from the checks tab after checks complete)
- [yes] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Palaksharma23** [comment]
@ShreyaPrasad1209 @manjotsidhu can you please once review my pull request .

**Comment by manjotsidhu** [comment]
@Palaksharma23 did you checked if these changes will work fine for mobile devices?

**Comment by Palaksharma23** [comment]
https://user-images.githubusercontent.com/87171452/143096851-0e201a88-c0ae-4914-beaf-5f711fba3654.mp4

**Comment by Palaksharma23** [comment]
@manjotsidhu yes sir after my last commit , these changes are working fine on every device

**Comment by Palaksharma23** [comment]
@manjotsidhu do i need to make more changes :)

**Comment by manjotsidhu** [comment]
@Shivansh2407

**Pull request merged**
